### PR TITLE
Update testing projects

### PR DESCRIPTION
**Pull request by dbelcham**
connects to #31 

WIP that should do the following
- [x] Remove ATT from AcceptanceTests project
  - [x] Add ASP specific acceptance tests
- [x] Create ComponentTests project
   - [x] Add more unit tests

### CODE REVIEW

**Comment by adamralph** [comment]
@dbelcham is there an issue that we can connect this with?

**Comment by dbelcham** [comment]
@adamralph There wasn't one. It was a piece of the bigger work for updating to v6 Core. Created an issue for it and linked in the original comment.

**Comment by adamralph** [comment]
:+1: @dbelcham, thanks.

BTW - it's better to use "connects to" as this prompts Waffle to connect the PR to the issue in the board view. I've changed it for this one.

**Comment by dbelcham** [comment]
@Particular/azure-maintainers PR is completed. Test coverage is at a point where we're comfortable with using it to proceed with the work to integrate with Core v6

- We have the tests built out in the new way that was requested by Particular/NServiceBus#3362 
- ComponentTests was flushed out to test Pub/Sub, Timeouts and Sagas
- All tests pass locally
- AcceptanceTests haven't been verified on the build server at this time (they don't run against branches)

**Comment by Scooletz** [comment]
I've read all the new tests and related issues (https://github.com/Particular/NServiceBus.AzureStoragePersistence/issues/31, https://github.com/Particular/NServiceBus/issues/3362). Are these new tests covering the persistence only are the seed for future persistence related tests? 
The tests do not cover the concurrency, sagas' visibility (like the issue in #26), etc. It's ok as we'd be red right now. This kind of tests is another dimension we should look at. If we're shifting to persistence only tests, that will be even easier to set up.

**Comment by dbelcham** [comment]
@Scooletz There are two sets of test (Component and Acceptance). Both are meant to be Persistence focused only. There likely are gaps in the acceptance tests as they stand now. All that has been done for acceptance tests is to bring the Persistence related tests in from the original suite. The component tests should be closer to being complete as they are more "unit" test like.

There is also a lot of work to be done to change these tests for v6. This work on the current state of the test is being done to get a "strong enough" baseline to verify that the changes for v6 have not broken something. As a result, we will almost definitely be adding more tests as we see gaps while working through the v6 updates.

**Comment by dbelcham** [comment]
Currently holding on this PR until we sort out the ability to get the AcceptanceTests project tests to run against ASQT instead of MSMQ like they did when I pushed the PR.

**Comment by kbaley** [comment]
@Particular/azure-maintainers This is ready to merge

**Pull request merged**
