### PR TITLE
[SPIKE] Async query for saga storage

### PR DESCRIPTION
**Pull request by danielmarbach**
This is a proposal to make the saga persister fully async. Unfortunately when I checked out the core v6 branch it didn't even compile.

Thoughts @Particular/azure-maintainers ?

### CODE REVIEW

**Comment by dbelcham** [comment]
This branch is still being converted to core v6. PR #39 is where we're working on it. The synchronous saga stuff isn't ready to be converted to async yet. We're waiting on PR #32 to be merged into develop. That PR is a significant re-write of how Sagas in this persister will work.

**Comment by danielmarbach** [comment]
@dbelcham Exactly. As you can see on this spike PR I'm extending #39 and #39 does not compile

Also #32 is based on V5 and not V6

I was reviewing the async work on #39 and stumbled over these issues. My idea with that spike was to provide hints how it could be done.

**Comment by dbelcham** [comment]
#39 doesn't compile. That is what we're currently working towards. That is to be expected right now.

#32 is based on v5. That was also a decision we made. It needs to be back ported to NServiceBus.Azure. Implementing it against v5 + holding off on the Saga update to v6 meant we would have the least amount of problems integrating the #32 changes when the time came.

**Comment by dbelcham** [comment]
@danielmarbach can you outline what the problems are with Timeout and/or PubSub? Those are the only two areas where we have worked on the v6 conversion.

**Comment by danielmarbach** [comment]
Btw. the intent of the PR/Spike is to help out. Nothing else.

Compiling should be a minimum requirement to be able to properly collaborate on a PR.

**Comment by dbelcham** [comment]
I completely understand that it should be. The only way to get this branch to compile is to 100% the conversion from v5 to v6. What I'm telling you is t

**Pull request closed without merging**
